model:
  base_learning_rate: 4.5e-6
  target: sgm.models.autoencoder.VQModel
  params:
    input_key: jpg
    monitor: "val/loss/rec"
    disc_start_iter: 50001
    embed_dim: 256
    n_embed: 16384

    ddconfig:
      attn_type: vanilla-xformers
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: sgm.modules.autoencoding.losses.GeneralLPIPSWithDiscriminator
      params:
        perceptual_weight: 1.0
        disc_start: 250001
        disc_weight: 0.8
        learn_logvar: false

        regularization_weights:
          vq_loss: 1.0

data:
  target: sgm.data.imagenet.ImageNetLoader
  params:
    batch_size: 24
    num_workers: 4
    prefetch_factor: 2
    shuffle: true

    train:
      root_dir: /path/to/ImageNet
      size: 256
      transform: true
    validation:
      root_dir: /path/to/ImageNet
      size: 256
      transform: true

lightning:
  strategy:
    target: pytorch_lightning.strategies.DDPStrategy
    params:
      find_unused_parameters: True

  modelcheckpoint:
    params:
      every_n_epochs: 1

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 50000

    image_logger:
      target: main.ImageLogger
      params:
        enable_autocast: False
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    precision: bf16
    devices: 0, 1, 2, 3
    limit_val_batches: 50
    benchmark: True
    accumulate_grad_batches: 1
    check_val_every_n_epoch: 1
